default:	DisplayCurrentTime_Caller
DisplayCurrentTime_Caller.o:	DisplayCurrentTime_Caller.c
	gcc	-c	DisplayCurrentTime_Caller.c	-o	DisplayCurrentTime_Caller.o

clean:
	rm -f DisplayCurrentTime_Caller.o
	rm -f DisplayCurrentTime_Caller
